config:
  exclusions:
    - 'AlexEven'
    - 'AntoineMille'
    - 'Asenar'
    - 'Azouz-Jribi'
    - 'DrySs'
    - 'FabienSerny'
    - 'LittleBigDev'
    - 'LucasC'
    - 'NinjaOfWeb'
    - 'PSAddonsTeam'
    - 'PierreRambaud'
    - 'Quetzacoalt91'
    - 'Shine-neko'
    - 'Shipow'
    - 'Shudrum'
    - 'TMMeilleur'
    - 'aleeks'
    - 'alegout'
    - 'anat'
    - 'antoin-m'
    - 'bLeveque42'
    - 'bmancone'
    - 'cocoweb94'
    - 'creack'
    - 'dSkrbic'
    - 'djfm'
    - 'emilien-puget'
    - 'eternoendless'
    - 'fatmaBouchekoua'
    - 'fchellypresta'
    - 'fouratachour'
    - 'franckbrignoli'
    - 'gRoussac'
    - 'gaillafr'
    - 'hadrich-hatem'
    - 'ishcherbakov'
    - 'jnadaud'
    - 'jocel1'
    - 'jolelievre'
    - 'jtabet'
    - 'julienbourdeau'
    - 'kelu95'
    - 'kompilorb'
    - 'mBertholino'
    - 'madef'
    - 'matks'
    - 'maximebiloe'
    - 'mickaelandrieu'
    - 'mmoustai'
    - 'nihco2'
    - 'rGaillard'
    - 'raphaelMalie'
    - 'sLorenzini'
    - 'sfroment'
    - 'tchauviere'
    - 'thierrymarianne'
    - 'tomlev'
    - 'toutantic'
    - 'vAugagneur'
    - 'vTerenti'
    - 'vchabot'
    - 'vincentbz'
    - 'vschoener'
    - 'xBorderie'
    - 'xGouley'
