config:
  fieldsWhitelist:
    - 'login'
    - 'id'
    - 'avatar_url'
    - 'html_url'
    - 'name'
    - 'company'
    - 'blog'
    - 'location'
    - 'bio'
  keepExcludedUsers: false
  exclusions:
    - 'AlexEven'
    - 'AntoineMille'
    - 'Asenar'
    - 'Azouz-Jribi'
    - 'CaptainYouz'
    - 'DrySs'
    - 'FabienSerny'
    - 'FlorianBergeron'
    - 'LittleBigDev'
    - 'LouiseBonnard'
    - 'LucasC'
    - 'Matt75'
    - 'NeOMakinG'
    - 'NinjaOfWeb'
    - 'PSAddonsTeam'
    - 'PierreRambaud'
    - 'Progi1984'
    - 'Quetzacoalt91'
    - 'Shine-neko'
    - 'Shipow'
    - 'Shudrum'
    - 'SimonGrn'
    - 'TMMeilleur'
    - 'YeLnatSs'
    - 'YosraAk'
    - 'aleeks'
    - 'alegout'
    - 'anat'
    - 'ansar21mallouli'
    - 'antoin-m'
    - 'atomiix'
    - 'bLeveque42'
    - 'bmancone'
    - 'boubkerbribri'
    - 'cocoweb94'
    - 'creack'
    - 'dSkrbic'
    - 'djfm'
    - 'emilien-puget'
    - 'eternoendless'
    - 'fatmaBouchekoua'
    - 'fchellypresta'
    - 'fouratachour'
    - 'franckbrignoli'
    - 'gRoussac'
    - 'gaillafr'
    - 'hadrich-hatem'
    - 'hibatallahAouadni'
    - 'ishcherbakov'
    - 'jnadaud'
    - 'jocel1'
    - 'jolelievre'
    - 'jtabet'
    - 'julienbourdeau'
    - 'kelu95'
    - 'khouloudbelguith'
    - 'kompilorb'
    - 'mBertholino'
    - 'madef'
    - 'marionf'
    - 'matks'
    - 'matthieu-rolland'
    - 'maximebiloe'
    - 'mbadrani'
    - 'mickaelandrieu'
    - 'mmoustai'
    - 'nesrineabdmouleh'
    - 'nihco2'
    - 'rGaillard'
    - 'raphaelMalie'
    - 'sLorenzini'
    - 'sfroment'
    - 'tchauviere'
    - 'thierrymarianne'
    - 'tomlev'
    - 'toutantic'
    - 'ttoine'
    - 'vAugagneur'
    - 'vTerenti'
    - 'vchabot'
    - 'vincentbz'
    - 'vschoener'
    - 'xBorderie'
    - 'xGouley'
