config:
  exclusions:
    - 'gRoussac'
    - 'rGaillard'
    - 'vAugagneur'
    - 'raphaelMalie'
    - 'julienbourdeau'
    - 'maximebiloe'
    - 'djfm'
    - 'jnadaud'
    - 'sfroment'
    - 'mickaelandrieu'
    - 'vchabot'
    - 'gaillafr'
    - 'aleeks'
    - 'Shudrum'
    - 'xBorderie'
    - 'kelu95'
    - 'Quetzacoalt91'
    - 'xGouley'
    - 'sLorenzini'
    - 'AlexEven'
    - 'FabienSerny'
    - 'thierrymarianne'
    - 'NinjaOfWeb'
    - 'bmancone'
    - 'Shipow'
    - 'tchauviere'
    - 'franckbrignoli'
    - 'Asenar'
    - 'nihco2'
    - 'jocel1'
    - 'antoin-m'
    - 'jtabet'
    - 'fatmaBouchekoua'
    - 'Shine-neko'
    - 'ishcherbakov'
