config:
  fieldsWhitelist:
    - 'login'
    - 'id'
    - 'avatar_url'
    - 'html_url'
    - 'name'
    - 'company'
    - 'blog'
    - 'location'
    - 'bio'
  extractEmailDomain: true
  keepExcludedUsers: false
  exclusions: []
