config:
  fieldsWhitelist:
    - 'login'
    - 'id'
    - 'avatar_url'
    - 'html_url'
    - 'name'
    - 'company'
    - 'blog'
    - 'location'
    - 'bio'
  extractEmailDomain: true
  keepExcludedUsers: false
  excludeRepositories:
    - "PrestaShop/PrestaShop-1.6"
    - "PrestaShop/PrestaShop-1.5"
  exclusions:
    - dependabot
    - dependabot[bot]
    - dependabot-preview
    - gitbook-bot
    - ps-jarvis
    - github-actions[bot]
